/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package gov.nih.niehs.ods.ga4gh.dos.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghCreateDataBundleRequest;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghCreateDataBundleResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghCreateDataObjectRequest;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghCreateDataObjectResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghDeleteDataBundleResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghDeleteDataObjectResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghGetDataBundleResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghGetDataBundleVersionsResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghGetDataObjectResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghGetDataObjectVersionsResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghListDataBundlesRequest;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghListDataBundlesResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghListDataObjectsRequest;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghListDataObjectsResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghUpdateDataBundleRequest;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghUpdateDataBundleResponse;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghUpdateDataObjectRequest;
import gov.nih.niehs.ods.ga4gh.dos.model.Ga4ghUpdateDataObjectResponse;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "gov.nih.niehs.ods.ga4gh.dos.codegen.languages.SpringCodegen", date = "2018-02-03T00:47:18.655Z")

@Api(value = "ga4gh", description = "the ga4gh API")
public interface Ga4ghApi {

    @ApiOperation(value = "Create a new Data Bundle", notes = "", response = Ga4ghCreateDataBundleResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghCreateDataBundleResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/databundles",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Ga4ghCreateDataBundleResponse> createDataBundle(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Ga4ghCreateDataBundleRequest body);


    @ApiOperation(value = "Make a new Data Object", notes = "", response = Ga4ghCreateDataObjectResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghCreateDataObjectResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/dataobjects",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Ga4ghCreateDataObjectResponse> createDataObject(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Ga4ghCreateDataObjectRequest body);


    @ApiOperation(value = "Delete a Data Bundle", notes = "", response = Ga4ghDeleteDataBundleResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghDeleteDataBundleResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/databundles/{data_bundle_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Ga4ghDeleteDataBundleResponse> deleteDataBundle(@ApiParam(value = "",required=true ) @PathVariable("data_bundle_id") String dataBundleId);


    @ApiOperation(value = "Delete a Data Object index entry", notes = "", response = Ga4ghDeleteDataObjectResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghDeleteDataObjectResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/dataobjects/{data_object_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<Ga4ghDeleteDataObjectResponse> deleteDataObject(@ApiParam(value = "",required=true ) @PathVariable("data_object_id") String dataObjectId);


    @ApiOperation(value = "Retrieve a Data Bundle", notes = "", response = Ga4ghGetDataBundleResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghGetDataBundleResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/databundles/{data_bundle_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Ga4ghGetDataBundleResponse> getDataBundle(@ApiParam(value = "",required=true ) @PathVariable("data_bundle_id") String dataBundleId,@ApiParam(value = "OPTIONAL If provided will return the requested version of the selected Data Bundle. Otherwise, only the latest version is returned.") @RequestParam(value = "version", required = false) String version);


    @ApiOperation(value = "", notes = "", response = Ga4ghGetDataBundleVersionsResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghGetDataBundleVersionsResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/databundles/{data_bundle_id}/versions",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Ga4ghGetDataBundleVersionsResponse> getDataBundleVersions(@ApiParam(value = "",required=true ) @PathVariable("data_bundle_id") String dataBundleId);


    @ApiOperation(value = "Retrieve a Data Object", notes = "", response = Ga4ghGetDataObjectResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghGetDataObjectResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/dataobjects/{data_object_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Ga4ghGetDataObjectResponse> getDataObject(@ApiParam(value = "",required=true ) @PathVariable("data_object_id") String dataObjectId,@ApiParam(value = "OPTIONAL If provided will return the requested version of the selected Data Object.") @RequestParam(value = "version", required = false) String version);


    @ApiOperation(value = "", notes = "", response = Ga4ghGetDataObjectVersionsResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghGetDataObjectVersionsResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/dataobjects/{data_object_id}/versions",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<Ga4ghGetDataObjectVersionsResponse> getDataObjectVersions(@ApiParam(value = "",required=true ) @PathVariable("data_object_id") String dataObjectId);


    @ApiOperation(value = "List the Data Bundles", notes = "", response = Ga4ghListDataBundlesResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghListDataBundlesResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/databundles/list",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Ga4ghListDataBundlesResponse> listDataBundles(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Ga4ghListDataBundlesRequest body);


    @ApiOperation(value = "List the Data Objects", notes = "", response = Ga4ghListDataObjectsResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghListDataObjectsResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/dataobjects/list",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Ga4ghListDataObjectsResponse> listDataObjects(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Ga4ghListDataObjectsRequest body);


    @ApiOperation(value = "Update a Data Bundle", notes = "", response = Ga4ghUpdateDataBundleResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghUpdateDataBundleResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/databundles/{data_bundle_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Ga4ghUpdateDataBundleResponse> updateDataBundle(@ApiParam(value = "",required=true ) @PathVariable("data_bundle_id") String dataBundleId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Ga4ghUpdateDataBundleRequest body);


    @ApiOperation(value = "Update a Data Object", notes = "", response = Ga4ghUpdateDataObjectResponse.class, tags={ "DataObjectService", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Ga4ghUpdateDataObjectResponse.class) })
    
    @RequestMapping(value = "/ga4gh/dos/v1/dataobjects/{data_object_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Ga4ghUpdateDataObjectResponse> updateDataObject(@ApiParam(value = "",required=true ) @PathVariable("data_object_id") String dataObjectId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Ga4ghUpdateDataObjectRequest body);

}
