/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.irods.jargon.ga4gh.dos.api;

import org.irods.jargon.ga4gh.dos.model.ServiceInfoResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-07T17:18:44.860Z")

@Api(value = "service-info", description = "the service-info API")
public interface ServiceInfoApi {

	@ApiOperation(value = "Returns service version and other information", nickname = "getServiceInfo", notes = "", response = ServiceInfoResponse.class, tags = {
			"DataRepositoryService", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "Service information returned successfully", response = ServiceInfoResponse.class) })
	@RequestMapping(value = "/service-info", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.GET)
	ResponseEntity<ServiceInfoResponse> getServiceInfo();

}
