/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.irods.jargon.ga4gh.dos.api;

import org.irods.jargon.ga4gh.dos.model.ServiceInfo;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-05-14T11:28:18.659Z")

@Api(value = "service-info", description = "the service-info API")
public interface ServiceInfoApi {

	@ApiOperation(value = "Get information about this implementation.", nickname = "getServiceInfo", notes = "May return service version and other information.", response = ServiceInfo.class, authorizations = {
			@Authorization(value = "authToken") }, tags = { "DataRepositoryService", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "Service information returned successfully", response = ServiceInfo.class) })
	@RequestMapping(value = "/service-info", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<ServiceInfo> getServiceInfo();

}
